version: "2"

networks:
  app-net:
    driver: bridge

volumes: 
  db_data:
    driver: local

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRESQL_PASSWORD=qweASD123@
      - POSTGRESQL_DATABASE=just_buy
    volumes:
      - db_data:/bitnami/postgresql
    networks:
      - app-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 25s
      retries: 10

  justbuy:
    build:
      context: ../project
      dockerfile: Dockerfile
    container_name: just_buy
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=qweASD123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8080:80"
      - "4430:443"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../project/Data/https:/https
    networks: 
      - app-net