// <auto-generated />

using JustBuyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustBuyApi.Migrations;

[DbContext(typeof(ProjectContext))]
[Migration("20221016165334_Initial")]
partial class Initial
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("JustBuyApi.Models.Role", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            b.Property<string>("Title")
                .IsRequired()
                .HasColumnType("longtext");

            b.HasKey("Id");

            b.ToTable("Roles");

            b.HasData(
                new
                {
                    Id = 1,
                    Title = "Администратор"
                },
                new
                {
                    Id = 2,
                    Title = "Клиент"
                });
        });

        modelBuilder.Entity("JustBuyApi.Models.User", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            b.Property<string>("Email")
                .IsRequired()
                .HasColumnType("varchar(255)");

            b.Property<int>("FK_Role_Id")
                .HasColumnType("int");

            b.Property<string>("FullName")
                .IsRequired()
                .HasColumnType("longtext");

            b.Property<string>("Password")
                .IsRequired()
                .HasColumnType("longtext");

            b.HasKey("Id");

            b.HasIndex("Email")
                .IsUnique();

            b.HasIndex("FK_Role_Id");

            b.ToTable("Users");

            b.HasData(
                new
                {
                    Id = 1,
                    Email = "admin@shop.ru",
                    FK_Role_Id = 1,
                    FullName = "Администратор",
                    Password = "QWEasd123"
                },
                new
                {
                    Id = 2,
                    Email = "user@shop.ru",
                    FK_Role_Id = 2,
                    FullName = "Клиент",
                    Password = "password"
                });
        });

        modelBuilder.Entity("JustBuyApi.Models.User", b =>
        {
            b.HasOne("JustBuyApi.Models.Role", "Role")
                .WithMany("Users")
                .HasForeignKey("FK_Role_Id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Role");
        });

        modelBuilder.Entity("JustBuyApi.Models.Role", b =>
        {
            b.Navigation("Users");
        });
#pragma warning restore 612, 618
    }
}